- name: install apt dependencies
  sudo: True
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - git-core
    - tmux
    - mosh
    - keychain
    - gawk
    - tree
    - zip
    - unzip
    - ruby
    - python-dev
    - python-setuptools
    - build-essential
    - autoconf
    - automake

- name: install pip
  sudo: True
  easy_install: name=pip

- name: install pip packages
  sudo: True
  pip: name={{ item }}
  with_items:
    - awscli
