- name: checkout wemux
  sudo: True
  git: repo=git://github.com/zolrath/wemux.git dest=/usr/local/share/wemux accept_hostkey=yes

- name: create wemux symlink
  sudo: True
  file: src=/usr/local/share/wemux/wemux dest=/usr/local/bin/wemux owner=root group=root mode=0755 state=link

- name: configure wemux/tmux
  copy: src={{ item.src }} dest={{ '/' + item.src.replace('_', '/') }} owner=root group=root mode={{ item.mode }}
  with_items:
    - { src: 'usr_local_etc_wemux.conf', mode: '0644' }
    - { src: 'etc_tmux.conf', mode: '0644' }
    - { src: 'usr_local_bin_tmux-users', mode: '0755' }
